### ISSUE TITLE
Assign a license to this repository

### ISSUE THREAD

**Issue by jamiebarrow** [kaiyote/intellij-codetours#1]
Hello! :)

I was looking for a plugin for IntelliJ that gave the same functionality as the Visual Studio Code extension and stumbled upon this repository, so I'd first like to say thanks for having this out there.

Since the VS CodeTour extension is MIT License, I would presume this repo is also along a similar kind of license, but I think it would be a good idea to provide a LICENSE.md explicitly to remove any doubt. While you're at it, maybe even a CONTRIBUTING.md docs if you would accept help from the general community :)

Thank you

**Comment by kaiyote** [comment]
Done & Done (tbqh, i had sort of forgotten i'd even started on this)
